project:
  type: website
  output-dir: docs

website:
  title: "PA446 Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: ExamplePage.qmd
        text: Page3

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

editor: visual

