project:
  type: website
  output-dir: docs
  resources: resume.pdf

website:
  title: "PA446 Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: ExamplePage.qmd
        text: Page3
      - text: Resume
        href: resume.pdf

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#9C3C27"
    linkcolor: "#ff33f0"
    monofont: courier new
      
editor: visual

